#CONFIG FILE FOR PWNAMON
#FOR BUILD GUIDE CHECK THIS REPO
#https://github.com/RasTacsko/DubRecen-PwnGang-Build-Guides
#
#RasTacsko
#2024
#DubRecen

ui.display.type = "waveshare_4"
ui.display.rotation = 180
ui.fps = 1

main.plugins.bt-tether.enabled = true
main.plugins.bt-tether.devices.android-phone.enabled = true

main.plugins.memtemp.enabled = true
main.plugins.memtemp.scale = "celsius"
main.plugins.memtemp.orientation = "horizontal"

main.plugins.pisugar3.enabled = true
main.plugins.pisugar3.shutdown = 1

main.plugins.pwnmenu.enabled = true

main.plugins.powerutils.enabled = true

main.plugins.gpsdeasy.enabled = true
main.plugins.gpsdeasy.host = "127.0.0.1"
main.plugins.gpsdeasy.port = 2947
main.plugins.gpsdeasy.device = "/dev/ttyACM0"
main.plugins.gpsdeasy.baud = 9600
main.plugins.gpsdeasy.fields = ['fix']

main.plugins.wardriver.enabled = true
main.plugins.wardriver.path = "/root/wardriver"
main.plugins.wardriver.ui.enabled = true
main.plugins.wardriver.ui.position.x = 5
main.plugins.wardriver.ui.position.y = 95

main.plugins.wardriver.wigle.enabled = true
main.plugins.wardriver.wigle.api_key = "YOURAPIKEYHERE"
main.plugins.wardriver.wigle.donate = false

main.plugins.wardriver.whitelist = []

main.plugins.enable_assoc.enabled = true

main.plugins.enable_deauth.enabled = true

main.plugins.instattack.enabled = false

main.plugins.clock.enabled = true

main.plugins.expv2.enabled = true
main.plugins.expv2.lvl_x_coord = 0
main.plugins.expv2.lvl_y_coord = 81
main.plugins.expv2.exp_x_coord = 38
main.plugins.expv2.exp_y_coord = 81
main.plugins.expv2.str_x_coord = 67
main.plugins.expv2.str_y_coord = 32
main.plugins.expv2.bar_symbols_count = 12

main.plugins.tweak_view.enabled = true

ui.faces.look_r = "/custom-faces/look_r.png"
ui.faces.look_l = "/custom-faces/look_l.png"
ui.faces.look_r_happy = "/custom-faces/look_r-happy.png"
ui.faces.look_l_happy = "/custom-faces/look_l-happy.png"
ui.faces.sleep = "/custom-faces/sleep.png"
ui.faces.sleep2 = "/custom-faces/sleep2.png"
ui.faces.awake = "/custom-faces/awake.png"
ui.faces.bored = "/custom-faces/bored.png"
ui.faces.intense = "/custom-faces/intense.png"
ui.faces.cool = "/custom-faces/cool.png"
ui.faces.happy = "/custom-faces/happy.png"
ui.faces.excited = "/custom-faces/excited.png"
ui.faces.grateful = "/custom-faces/grateful.png"
ui.faces.motivated = "/custom-faces/motivated.png"
ui.faces.demotivated = "/custom-faces/demotivated.png"
ui.faces.smart = "/custom-faces/smart.png"
ui.faces.lonely = "/custom-faces/lonely.png"
ui.faces.sad = "/custom-faces/sad.png"
ui.faces.angry = "/custom-faces/angry.png"
ui.faces.friend = "/custom-faces/friend.png"
ui.faces.broken = "/custom-faces/broken.png"
ui.faces.debug = "/custom-faces/debug.png"
ui.faces.upload = "/custom-faces/upload.png"
ui.faces.upload1 = "/custom-faces/upload1.png"
ui.faces.upload2 = "/custom-faces/upload2.png"
ui.faces.png = true
ui.faces.position_x = 0
ui.faces.position_y = 34
ui.invert = true
